---
- job: 
    name: ansible-lint
    run: playbooks/ansible-lint/run.yaml

- job:
    name: dcolicense
    run: playbooks/dcolicense/run.yaml

- job:
    name: devstack
    run: playbooks/devstack/run.yaml

- job:
    name: ensure-buildah
    run: playbooks/ensure-buildah/run.yaml

- job:
    name: flake8
    run: playbooks/flake8/run.yaml

- job:
    name: hadolint
    run: playbooks/hadolint/run.yaml

- job:
    name: mypy
    run: playbooks/mypy/run.yaml

- job:
    name: yamllint
    run: playbooks/yamllint/run.yaml

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - ansible-lint
        - yamllint
    gate:
      jobs:
        - ansible-lint
        - yamllint
